version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "dotnet/sdk"
        update-types: ["version-update:semver-major"]
      - dependency-name: "dotnet/aspnet"
        update-types: ["version-update:semver-major"]